//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEV_Task_05.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KEV_Task_05.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 11111111111111111111111111111111111111111111111111
        ///12100000000000000001111111110000000111111011010001
        ///10111110101011110100100000000111110000001001010101
        ///10100010101010000110110111110000011111101101010101
        ///10101010101011110100100100010111000000100101000101
        ///10101000101000010110111101010101011110110101111101
        ///10101011101111010010100001000101000010000000000001
        ///10101010000001111011111101111101011011111111011101
        ///10001010111100000000000001000000010000010000000131
        ///11111111111111111111111111111111111111111111111111.
        /// </summary>
        internal static string levelOne {
            get {
                return ResourceManager.GetString("levelOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1111111111111111111111111111111111111111111111111111
        ///1000020000000000100000000000000000000400000000000001
        ///1011111111110111111111101111111111111111111111111111
        ///1000100000000000000000100000000000000000000000000101
        ///1010101111111111111111111111111111111111111111110101
        ///1010100000000000000000000000000000100000000000310001
        ///1010111111111111111111111111111110111111111011110101
        ///1010000000000000000000000000000000000000100000000101
        ///1011111111111111111111111110111111111110111111111101
        ///10100000000000000000000000000000000 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string levelThree {
            get {
                return ResourceManager.GetString("levelThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 111111111111111111111111111111111111111111
        ///100000001010000000000000000140010001000001
        ///101110101010111111111111110101010101011101
        ///101010101010100000000000010101010101010101
        ///101010101010101101111111010101010101010101
        ///101010101010101000000001010101010101010101
        ///101010101010101011111101010101010111010001
        ///101010101010101010000101010101010101010101
        ///101010101010001010110111010101010101010101
        ///101010100010101110130101010111010101010101
        ///100010111010101010111101010101010101010101
        ///111010101010101010000001010101010101011 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string levelTwo {
            get {
                return ResourceManager.GetString("levelTwo", resourceCulture);
            }
        }
    }
}
